Fix schema for inclusion in yast2-schema (profile.rnc) (bsc#1170886)
Formerly this was a standalone schema but now it's included in the AY schema
so we need to remove the 'start' declaration
and remove the defines that conflict with other packages.
(Inlining most of defines makes the schema more readable too)

This fixes these errors:
yast2-schema-4.3.0/src/rng/users.rng:113:25: error: multiple definitions of "expire" without "combine" attribute
yast2-schema-4.3.0/src/rng/reporting.rng:69:26: error: multiple definitions of "timeout" without "combine" attribute
yast2-schema-4.3.0/src/rng/scripts.rng:197:27: error: multiple definitions of "filename" without "combine" attribute
yast2-schema-4.3.0/src/rng/profile.rng:355:10: error: multiple definitions of start without "combine" attribute